name: "generate-snake-game-from-github-contribution-grid"
description: "Generates a snake game from a GitHub user's contributions grid. Outputs the animation as GIF or SVG."
author: "platane"

inputs:
  github_user_name:
    description: "GitHub username to fetch the contributions from"
    required: true

  github_token:
    description: "GitHub token used to fetch the contribution calendar. Defaults to the action token if empty."
    required: false
    default: ${{ github.token }}

  outputs:
    description: |
      List of files to generate. One file per line.
      Each output can be customized with options as a query string.

      Supported query string options:
      - palette:     A preset of colors, one of [github, github-dark, github-light]
      - color_snake: Color of the snake
      - color_dots:  Comma-separated list of dot colors.
                     The first one is for 0 contributions, then from low to high contributions.
                     Exactly 5 colors are expected.

      Example:
        outputs: |
          dark.svg?palette=github-dark&color_snake=blue
          light.svg?color_snake=#7845ab
          ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
    required: false

runs:
  using: docker
  image: docker://platane/snk@sha256:96390294299275740e5963058c9784c60c5393b3b8b16082dcf41b240db791f9
